import { StyleSheet } from 'react-native';

export default function createDashboardStyles(isDark) {
  return StyleSheet.create({
    title: {
      fontSize: 32,
      fontWeight: '800',
      marginBottom: 8,
      color: isDark ? '#f8fafc' : '#0f172a',
    },
    subtitle: {
      color: isDark ? '#cbd5e1' : '#475569',
      marginBottom: 20,
      lineHeight: 22,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    cardLabel: {
      fontSize: 14,
      color: isDark ? '#94a3b8' : '#6b7280',
      marginBottom: 6,
    },
    cardValue: {
      fontSize: 28,
      fontWeight: '700',
      color: isDark ? '#f8fafc' : '#111827',
    },
    cardMeta: {
      marginTop: 8,
      color: isDark ? '#94a3b8' : '#6b7280',
      fontSize: 13,
    },
    sectionTitle: { fontSize: 19, fontWeight: '800', color: isDark ? '#f8fafc' : '#0f172a', marginBottom: 12 },
    input: { borderWidth: 1, borderColor: isDark ? '#334155' : '#cbd5e1', borderRadius: 10, color: isDark ? '#f8fafc' : '#0f172a', padding: 12, marginBottom: 12, backgroundColor: isDark ? '#1e293b' : '#ffffff' },
    placeholder: { color: isDark ? '#94a3b8' : '#64748b' },
    searchResult: { borderTopWidth: 1, borderTopColor: isDark ? '#334155' : '#e5e7eb', paddingVertical: 10 },
    resultName: { color: isDark ? '#f8fafc' : '#0f172a', fontSize: 16, fontWeight: '700' },
    selection: { marginTop: 12 },
    fieldLabel: { color: isDark ? '#f8fafc' : '#0f172a', fontWeight: '700', marginTop: 6, marginBottom: 8 },
    optionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
    option: { borderWidth: 1, borderColor: isDark ? '#475569' : '#cbd5e1', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
    optionSelected: { backgroundColor: '#16a34a', borderColor: '#16a34a' },
    optionText: { color: isDark ? '#cbd5e1' : '#475569', fontSize: 13 },
    optionTextSelected: { color: '#ffffff', fontWeight: '700' },
    primaryButton: { alignItems: 'center', backgroundColor: '#16a34a', borderRadius: 10, padding: 13, marginTop: 12 },
    primaryButtonText: { color: '#ffffff', fontWeight: '800' },
    disabled: { opacity: 0.65 },
    error: { color: isDark ? '#fca5a5' : '#b91c1c', marginTop: 10, lineHeight: 20 },
    mealItem: { borderTopWidth: 1, borderTopColor: isDark ? '#334155' : '#e5e7eb', paddingTop: 12, marginTop: 12 },
    mealDetails: { marginBottom: 9 },
    quantityControls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconButton: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: isDark ? '#334155' : '#e2e8f0' },
    iconButtonText: { color: isDark ? '#f8fafc' : '#0f172a', fontSize: 19, fontWeight: '700' },
    quantityText: { minWidth: 24, textAlign: 'center', color: isDark ? '#f8fafc' : '#0f172a', fontWeight: '700' },
    deleteButton: { marginLeft: 4, paddingHorizontal: 8, paddingVertical: 6 },
    deleteText: { color: '#dc2626', fontWeight: '700' },
    imageSearch: { borderTopWidth: 1, borderTopColor: isDark ? '#334155' : '#e5e7eb', marginTop: 18, paddingTop: 16 },
    secondaryButton: { alignItems: 'center', borderWidth: 1, borderColor: isDark ? '#64748b' : '#94a3b8', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
    secondaryButtonText: { color: isDark ? '#e2e8f0' : '#334155', fontWeight: '700' },
    imagePreview: { width: '100%', height: 220, borderRadius: 10, marginTop: 8, resizeMode: 'cover' },
    analyzeButton: { flexGrow: 1, marginTop: 0 },
    aiMatch: { borderTopWidth: 1, borderTopColor: isDark ? '#334155' : '#e5e7eb', marginTop: 12, paddingTop: 12 },
  });
}
